apiVersion: v1
kind: Pod
metadata:
  name: busy-box-pod
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sleep"
      - "3600"
  restartPolicy: Never
